# Generated by Django 4.1.7 on 2023-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="passangers",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="people",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="time",
            field=models.DateTimeField(null=True),
        ),
    ]
