# Generated by Django 4.1.7 on 2023-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_transport", "0002_car_passangers_task_people_task_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
