# Generated by Django 4.1.7 on 2023-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_transport", "0003_task_date_alter_task_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
