# Generated by Django 4.1.7 on 2023-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_transport", "0004_alter_task_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="fuel",
            new_name="fuel_after",
        ),
        migrations.AddField(
            model_name="task",
            name="fuel_before",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
