# Generated by Django 4.1.7 on 2023-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_transport", "0005_rename_fuel_task_fuel_after_task_fuel_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="pokazatel",
            field=models.FloatField(null=True),
        ),
    ]
